// <auto-generated />
using System;
using Bumbodium.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bumbodium.Data.Migrations
{
    [DbContext(typeof(BumbodiumContext))]
    partial class BumbodiumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Bumbodium.Data.DBModels.Availability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"), 1L, 1);

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Availability");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("Branch");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Den Bosch",
                            Country = 0,
                            HouseNumber = "1",
                            PostalCode = "0000 AA",
                            Street = "01"
                        });
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.BranchEmployee", b =>
                {
                    b.Property<int>("FiliaalId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FiliaalId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("BranchEmployee");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Name")
                        .HasColumnType("int");

                    b.Property<int>("SurfaceAreaInM2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BranchId = 1,
                            Description = "Vegetables_Fruit",
                            Name = 0,
                            SurfaceAreaInM2 = 50
                        },
                        new
                        {
                            Id = 2,
                            BranchId = 1,
                            Description = "Meat",
                            Name = 1,
                            SurfaceAreaInM2 = 140
                        },
                        new
                        {
                            Id = 3,
                            BranchId = 1,
                            Description = "Fish",
                            Name = 2,
                            SurfaceAreaInM2 = 80
                        },
                        new
                        {
                            Id = 4,
                            BranchId = 1,
                            Description = "Cheese_Milk",
                            Name = 3,
                            SurfaceAreaInM2 = 200
                        },
                        new
                        {
                            Id = 5,
                            BranchId = 1,
                            Description = "Bread",
                            Name = 4,
                            SurfaceAreaInM2 = 150
                        },
                        new
                        {
                            Id = 6,
                            BranchId = 1,
                            Description = "Cosmetics",
                            Name = 5,
                            SurfaceAreaInM2 = 180
                        },
                        new
                        {
                            Id = 7,
                            BranchId = 1,
                            Description = "Checkout",
                            Name = 6,
                            SurfaceAreaInM2 = 90
                        },
                        new
                        {
                            Id = 8,
                            BranchId = 1,
                            Description = "Stockroom",
                            Name = 7,
                            SurfaceAreaInM2 = 100
                        },
                        new
                        {
                            Id = 9,
                            BranchId = 1,
                            Description = "InformationDesk",
                            Name = 8,
                            SurfaceAreaInM2 = 70
                        });
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.DepartmentEmployee", b =>
                {
                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkFunction")
                        .HasColumnType("int");

                    b.HasKey("DepartmentId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("DepartmentEmployee");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 4,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 5,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 6,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 7,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 8,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 9,
                            EmployeeId = "19f7d479-542a-408b-9016-0561e3e70f65",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "2e835447-b339-4a55-9a74-c0d8449bca5c",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            EmployeeId = "2e835447-b339-4a55-9a74-c0d8449bca5c",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            EmployeeId = "2e835447-b339-4a55-9a74-c0d8449bca5c",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 7,
                            EmployeeId = "44128c29-b648-431e-89f4-7a105f79b00c",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 8,
                            EmployeeId = "44128c29-b648-431e-89f4-7a105f79b00c",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 9,
                            EmployeeId = "44128c29-b648-431e-89f4-7a105f79b00c",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 4,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 5,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 6,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 7,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 8,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 9,
                            EmployeeId = "5782d108-8865-40f8-b3b7-ced82309983f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "5989a56b-4d00-4213-9b73-34f80701836b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            EmployeeId = "5989a56b-4d00-4213-9b73-34f80701836b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            EmployeeId = "5989a56b-4d00-4213-9b73-34f80701836b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 4,
                            EmployeeId = "5989a56b-4d00-4213-9b73-34f80701836b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 5,
                            EmployeeId = "5989a56b-4d00-4213-9b73-34f80701836b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 2,
                            EmployeeId = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 3,
                            EmployeeId = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 4,
                            EmployeeId = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 5,
                            EmployeeId = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "a20cddd4-9704-439f-94bc-95f4659ce543",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "a357223e-5d1e-461e-b1ad-3a8592f548dd",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "b74ddd14-6340-4840-95c2-db12554843e5",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "b93d704f-a4ae-413f-a587-0b597bbe6a9f",
                            WorkFunction = 0
                        },
                        new
                        {
                            DepartmentId = 1,
                            EmployeeId = "bdece4e2-3ed9-4008-8878-65884c142394",
                            WorkFunction = 0
                        });
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateInService")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOutService")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("EmployeeID");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeID = "b74ddd14-6340-4840-95c2-db12554843e5",
                            Birthdate = new DateTime(1989, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2006, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "j.vangeest@bumbodium.nl",
                            FirstName = "Jan",
                            LastName = "Geest",
                            MiddleName = "van",
                            PhoneNumber = "+31 6 56927484",
                            Type = 0
                        },
                        new
                        {
                            EmployeeID = "2e835447-b339-4a55-9a74-c0d8449bca5c",
                            Birthdate = new DateTime(1, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2001, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Johnny@vos.nl",
                            FirstName = "Johnny",
                            LastName = "Vos",
                            PhoneNumber = "+31 777777777",
                            Type = 0
                        },
                        new
                        {
                            EmployeeID = "19f7d479-542a-408b-9016-0561e3e70f65",
                            Birthdate = new DateTime(1, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2001, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Martijs@Martijs.Martijs",
                            FirstName = "Martijs",
                            LastName = "Martijs",
                            PhoneNumber = "Martijs",
                            Type = 0
                        },
                        new
                        {
                            EmployeeID = "44128c29-b648-431e-89f4-7a105f79b00c",
                            Birthdate = new DateTime(1975, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2009, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Heinz@vonschmichtelstein.de",
                            FirstName = "Heinz",
                            LastName = "Schmichtelstein",
                            MiddleName = "von",
                            PhoneNumber = "+49 420 69 7777",
                            Type = 1
                        },
                        new
                        {
                            EmployeeID = "5782d108-8865-40f8-b3b7-ced82309983f",
                            Birthdate = new DateTime(2007, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2009, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Bliksem@martijnshamster.nl",
                            FirstName = "Bliksem",
                            LastName = "Snel",
                            PhoneNumber = "+31 snel",
                            Type = 1
                        },
                        new
                        {
                            EmployeeID = "5989a56b-4d00-4213-9b73-34f80701836b",
                            Birthdate = new DateTime(2005, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2009, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Lobbus@kjell.nl",
                            FirstName = "Lobbus",
                            LastName = "Good boy",
                            PhoneNumber = "+31 1684867685",
                            Type = 1
                        },
                        new
                        {
                            EmployeeID = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            Birthdate = new DateTime(1988, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Paula@campina.nl",
                            FirstName = "Paula",
                            LastName = "Campina",
                            PhoneNumber = "+31 612345678",
                            Type = 0
                        },
                        new
                        {
                            EmployeeID = "a20cddd4-9704-439f-94bc-95f4659ce543",
                            Birthdate = new DateTime(1957, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2019, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Henkie@Wauwzerz.nl",
                            FirstName = "Henkie",
                            LastName = "T",
                            PhoneNumber = "ten minste vijf",
                            Type = 1
                        },
                        new
                        {
                            EmployeeID = "a357223e-5d1e-461e-b1ad-3a8592f548dd",
                            Birthdate = new DateTime(1999, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2014, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Katriene@smedensberg.com",
                            FirstName = "Katriene",
                            LastName = "Smedensberg",
                            PhoneNumber = "+31 99999999",
                            Type = 0
                        },
                        new
                        {
                            EmployeeID = "b93d704f-a4ae-413f-a587-0b597bbe6a9f",
                            Birthdate = new DateTime(1900, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2002, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Henk@henk.nl",
                            FirstName = "Henk",
                            LastName = "Henk",
                            PhoneNumber = "+31 6666666666",
                            Type = 1
                        },
                        new
                        {
                            EmployeeID = "bdece4e2-3ed9-4008-8878-65884c142394",
                            Birthdate = new DateTime(1869, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateInService = new DateTime(2002, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Henk@maardanstoer.nl",
                            FirstName = "Henk",
                            LastName = "Stoer",
                            MiddleName = "maar dan",
                            PhoneNumber = "+31 123123123",
                            Type = 1
                        });
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Forecast", b =>
                {
                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("AmountExpectedColis")
                        .HasColumnType("int");

                    b.Property<int>("AmountExpectedCustomers")
                        .HasColumnType("int");

                    b.Property<int>("AmountExpectedEmployees")
                        .HasColumnType("int");

                    b.Property<int>("AmountExpectedHours")
                        .HasColumnType("int");

                    b.Property<int?>("StandardsId")
                        .HasColumnType("int");

                    b.HasKey("Date", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StandardsId");

                    b.ToTable("Forecast");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Presence", b =>
                {
                    b.Property<int>("PresenceId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("AlteredClockInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AlteredClockOutDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClockInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ClockOutDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("PresenceId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Presence");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShiftId"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ShiftEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("ShiftId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Shift");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Standards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Country")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1048)
                        .HasColumnType("nvarchar(1048)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Standards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = 0,
                            Description = "aantal minuten per Coli uitladen.",
                            Subject = "Coli",
                            Value = 5
                        },
                        new
                        {
                            Id = 2,
                            Country = 0,
                            Description = "aantal minuten Vakken vullen per Coli.",
                            Subject = "StockingShelves",
                            Value = 30
                        },
                        new
                        {
                            Id = 3,
                            Country = 0,
                            Description = "1 Kasiere per uur per aantal klanten.",
                            Subject = "Cashier",
                            Value = 30
                        },
                        new
                        {
                            Id = 4,
                            Country = 0,
                            Description = "1 medewerker per customer per uur per aantal klanten.",
                            Subject = "Employee",
                            Value = 100
                        },
                        new
                        {
                            Id = 5,
                            Country = 0,
                            Description = "aantal seconde voor medewerker per customer per meter.",
                            Subject = "Mirror",
                            Value = 30
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b74ddd14-6340-4840-95c2-db12554843e5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "500ebeb9-1886-4ba1-98c7-c4d958399973",
                            Email = "j.vangeest@bumbodium.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "J.VANGEEST@BUMBODIUM.NL",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEHmI0mknsA9j76FX9/oUU3f1ZAjhc0o8gk91nE65qQ5zuyjnmDlncwrIZ8VKTj7o8g==",
                            PhoneNumber = "+31 6 56927484",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "add5fd45-51a6-4b51-b536-9e43f05b8052",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = "19f7d479-542a-408b-9016-0561e3e70f65",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4769e5da-b3ea-4e81-8398-595aa8395586",
                            Email = "Martijs@Martijs.Martijs",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MARTIJS@MARTIJS.MARTIJS",
                            PasswordHash = "AQAAAAEAACcQAAAAEKVq/oLvkb56zrdB1etzGXugHvJCSbuS08rVX8TqeWbT0k0PRBWDgFqjme36k81c/g==",
                            PhoneNumber = "Martijs",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c397f6ce-e663-4b0f-88cb-a4922707b19e",
                            TwoFactorEnabled = false,
                            UserName = "Martijs@Martijs.Martijs"
                        },
                        new
                        {
                            Id = "2e835447-b339-4a55-9a74-c0d8449bca5c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dea4b739-a72c-46eb-9d57-dd6938bfeaf4",
                            Email = "Johnny@vos.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "JOHNNY@VOS.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEMliA6+1UgSjZavmDVrXfILx+GKC/iL6QrYbj5DdVhk7iB/h7rmowSA/iK5ZEJPLdw==",
                            PhoneNumber = "+31 5",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74f1a0a4-e5a9-4723-b56e-4192b23bf596",
                            TwoFactorEnabled = false,
                            UserName = "Johnny@vos.nl"
                        },
                        new
                        {
                            Id = "44128c29-b648-431e-89f4-7a105f79b00c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9960adc2-da5c-4439-a6fd-346a7b7e6a7f",
                            Email = "Heinz@vonschmichtelstein.de",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HEINZ@VONSCHMICHTELSTEIN.DE",
                            PasswordHash = "AQAAAAEAACcQAAAAEBT8lKWjd5DXBSd9PSykDk2PjOPHV4XH5wZ++TaO4nNYRlgofAAHDLX4p2HCZ3jYbw==",
                            PhoneNumber = "+49 420 69 7777",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e6b4e793-90fd-48c7-ac9d-4dbed99826a5",
                            TwoFactorEnabled = false,
                            UserName = "Heinz@vonschmichtelstein.de"
                        },
                        new
                        {
                            Id = "5782d108-8865-40f8-b3b7-ced82309983f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "56a1124f-f52d-4ea3-84ac-d19c406994bf",
                            Email = "Bliksem@martijnshamster.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "BLIKSEM@MARTIJNSHAMSTER.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEIbyiUVlmg2Q1vw1Bx3qHaqtqT520TekvwFimUhFSEL1e7s5Pwm2TVF0giIpPlJi9w==",
                            PhoneNumber = "+31 snel",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a738ec7e-3f21-4d12-a432-d98d96fb779e",
                            TwoFactorEnabled = false,
                            UserName = "Bliksem@martijnshamster.nl"
                        },
                        new
                        {
                            Id = "5989a56b-4d00-4213-9b73-34f80701836b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bc26a12-ae14-4a5f-8383-0ee8ecb34bb6",
                            Email = "Lobbus@kjell.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "LOBBUS@KJELL.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEFnJPjjYxeczPQVkdO6mncH5AhXxkI7iq2/kpiZv34BA2/6NgHaS0rfVe/gfxv620w==",
                            PhoneNumber = "+31 6 67215943",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9dce1a89-14bd-490b-b9f3-8154f62e97b8",
                            TwoFactorEnabled = false,
                            UserName = "Lobbus@kjell.nl"
                        },
                        new
                        {
                            Id = "5fd33111-a002-4ef1-a301-8c4e4e31e20b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8ee75753-43f9-4180-aac8-4b93a6583cf3",
                            Email = "Paula@campina.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "PAULA@CAMPINA.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEH1EyOs4h0ClBEAc4VuLBu6CIyEmxOnVArLi0ty7YB1QjIAKMocslnJaJkknKsMyBw==",
                            PhoneNumber = "+31 612345678",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bad5cdfb-f67a-4dfb-a264-d8e27d8abe32",
                            TwoFactorEnabled = false,
                            UserName = "Paula@campina.nl"
                        },
                        new
                        {
                            Id = "a20cddd4-9704-439f-94bc-95f4659ce543",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "4bdbf194-a4a7-4017-929b-1a4ab6e9737f",
                            Email = "Henkie@Wauwzerz.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HENKIE@WAUWZERZ.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEBg5GRxO+TiYS0yIDZ9GJ9ipTQiEDvjA5Fu2DFFZG/2f1I05SnefI+dHI4puJxUdug==",
                            PhoneNumber = "ten minste vijf",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e2f3529-2d51-40ec-9529-818e9b4eef66",
                            TwoFactorEnabled = false,
                            UserName = "Henkie@Wauwzerz.nl"
                        },
                        new
                        {
                            Id = "a357223e-5d1e-461e-b1ad-3a8592f548dd",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f25a5fb0-e7a6-4a68-b5cf-e83d63f85970",
                            Email = "Katriene@smedensberg.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "KATRIENE@SMEDENSBERG.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEFsrHp84Q6hD7cEitvLwiMn7A+R0lAah7WX2HSJb7uNoK/LEQ/+jpYOI92epUBTPew==",
                            PhoneNumber = "+31 99999999",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b18623e6-d9b9-48e2-b16e-fea59a3fff70",
                            TwoFactorEnabled = false,
                            UserName = "Katriene@smedensberg.com"
                        },
                        new
                        {
                            Id = "b93d704f-a4ae-413f-a587-0b597bbe6a9f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f1947bcd-4367-4d99-8c82-fc3dc73eebfb",
                            Email = "Henk@henk.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HENK@HENK.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEP5aGms8gbm8xiziEJWnDqlPJsXCnRMOzeZJ4IGg9nFdLTycetgArXwuk2hLQN+rEQ==",
                            PhoneNumber = "+31 6666666666",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f9937927-9922-4e3a-806d-614475401376",
                            TwoFactorEnabled = false,
                            UserName = "Henk@henk.nl"
                        },
                        new
                        {
                            Id = "bdece4e2-3ed9-4008-8878-65884c142394",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0dc8cad7-8f5c-458e-8bb8-bb09df94411f",
                            Email = "Henk@maardanstoer.nl",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HENK@MAARDANSTOER.NL",
                            PasswordHash = "AQAAAAEAACcQAAAAEFlRIgUzYXjeQ4UvSKDpVIQxa+oAVuyGZ7p8zCYXpBQCJ4f+e2Cq9ImQPV4M4PYouQ==",
                            PhoneNumber = "+31 123123123",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f7ab2ff1-f111-4778-bc2a-0ab976ea8343",
                            TwoFactorEnabled = false,
                            UserName = "Henk@maardanstoer.nl"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Availability", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Employee", "Employee")
                        .WithMany("Availability")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.BranchEmployee", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Employee", "Employee")
                        .WithMany("PartOFFiliaal")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bumbodium.Data.DBModels.Branch", "Filiaal")
                        .WithMany("PartOFEmployee")
                        .HasForeignKey("FiliaalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Filiaal");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Department", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.DepartmentEmployee", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Department", "Department")
                        .WithMany("PartOFEmployee")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bumbodium.Data.DBModels.Employee", "Employee")
                        .WithMany("PartOFDepartment")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Employee", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "Account")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Forecast", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Department", "Department")
                        .WithMany("Forecast")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bumbodium.Data.DBModels.Standards", null)
                        .WithMany("ForecastId")
                        .HasForeignKey("StandardsId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Presence", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Employee", "Employee")
                        .WithMany("Presence")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Shift", b =>
                {
                    b.HasOne("Bumbodium.Data.DBModels.Department", "Department")
                        .WithMany("Shifts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bumbodium.Data.DBModels.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Branch", b =>
                {
                    b.Navigation("PartOFEmployee");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Department", b =>
                {
                    b.Navigation("Forecast");

                    b.Navigation("PartOFEmployee");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Employee", b =>
                {
                    b.Navigation("Availability");

                    b.Navigation("PartOFDepartment");

                    b.Navigation("PartOFFiliaal");

                    b.Navigation("Presence");

                    b.Navigation("Shifts");
                });

            modelBuilder.Entity("Bumbodium.Data.DBModels.Standards", b =>
                {
                    b.Navigation("ForecastId");
                });
#pragma warning restore 612, 618
        }
    }
}
